server:
  port: 9000
spring:
  rabbitmq:
    host: your mq server ip
    username: guest
    password: guest
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
ribbon:
  ReadTimeout: 10000
  SocketTimeout: 30000
