server:
  port: 7001
spring:
  redis:
    host: your redis server ip
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: your mq server ip
    username: guest
    password: guest
mybatis:
  type-aliases-package: cn.edu.tju.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
