server:
  port: 7000
spring:
  rabbitmq:
    host: your mq server ip
    username: guest
    password: guest
  redis:
    host: your redis server ip
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  type-aliases-package: cn.edu.tju.pojo
  mapper-locations: classpath:mappers/*.xml
